// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TheAngryByrd.TypeSafeInternals")>]
[<assembly: AssemblyProductAttribute("TheAngryByrd.TypeSafeInternals")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-24T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","200b44716081ccdb3efe1256e241c61286b5a658")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TheAngryByrd.TypeSafeInternals"
    let [<Literal>] AssemblyProduct = "TheAngryByrd.TypeSafeInternals"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-24T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "200b44716081ccdb3efe1256e241c61286b5a658"
