// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TheAngryByrd.Myriad.Plugins.TypeSafeInternals")>]
[<assembly: AssemblyProductAttribute("TypeSafeInternals")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2017-03-17T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","269fb0305ac37531bad75a6b00a0af7653776a23")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TheAngryByrd.Myriad.Plugins.TypeSafeInternals"
    let [<Literal>] AssemblyProduct = "TypeSafeInternals"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "269fb0305ac37531bad75a6b00a0af7653776a23"
