// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TheAngryByrd.Myriad.Plugins.TypeSafeInternals")>]
[<assembly: AssemblyProductAttribute("TheAngryByrd.TypeSafeInternals")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-24T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e5eef4dfc91cd9a363443e4942ce729aa59d9195")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TheAngryByrd.Myriad.Plugins.TypeSafeInternals"
    let [<Literal>] AssemblyProduct = "TheAngryByrd.TypeSafeInternals"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-24T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "e5eef4dfc91cd9a363443e4942ce729aa59d9195"
