// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TheAngryByrd.Myriad.Plugins.TypeSafeInternals.Tests")>]
[<assembly: AssemblyProductAttribute("TheAngryByrd.TypeSafeInternals")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-24T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","b60a838c25b86d83ca8a536f02f5e33d2125efe7")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TheAngryByrd.Myriad.Plugins.TypeSafeInternals.Tests"
    let [<Literal>] AssemblyProduct = "TheAngryByrd.TypeSafeInternals"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-24T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "b60a838c25b86d83ca8a536f02f5e33d2125efe7"
